# Generated by Django 4.1 on 2022-08-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseStatus',
            fields=[
                ('name', models.CharField(default='OK', max_length=100, primary_key=True, serialize=False, verbose_name='наименование')),
            ],
            options={
                'db_table': 'response_status',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='ТГ user_id')),
                ('name', models.CharField(db_index=True, default='', max_length=1000, verbose_name='имя')),
                ('username', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ТГ username')),
                ('referer_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ТГ user_id реферала')),
                ('balance_requests', models.PositiveSmallIntegerField(db_index=True, default=10, verbose_name='баланс запросов')),
                ('access', models.CharField(default='allowed', max_length=50, verbose_name='доступ к боту')),
                ('start_time_limited', models.PositiveIntegerField(blank=True, null=True, verbose_name='время ограничения доступа')),
                ('position', models.CharField(default='user', max_length=50, verbose_name='роль пользователя')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='пароль')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='когда добавился')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
            ],
            options={
                'db_table': 'telegram_users',
                'ordering': ['date_joined'],
            },
        ),
        migrations.CreateModel(
            name='TypesRequest',
            fields=[
                ('name', models.CharField(default='keyword', max_length=100, primary_key=True, serialize=False, verbose_name='наименование')),
            ],
            options={
                'db_table': 'type_request',
            },
        ),
        migrations.CreateModel(
            name='WBSubject',
            fields=[
                ('objectId', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id предмета')),
                ('objectName', models.CharField(db_index=True, max_length=300, unique=True, verbose_name='предмет')),
                ('parentId', models.IntegerField(db_index=True, verbose_name='id категории')),
                ('parentName', models.CharField(max_length=300, verbose_name='категория')),
                ('isVisible', models.CharField(max_length=50, verbose_name='isVisible')),
            ],
            options={
                'db_table': 'wb_subjects',
            },
        ),
        migrations.CreateModel(
            name='TelegramUserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_request', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('text_request', models.CharField(max_length=1000, verbose_name='текст запроса')),
                ('response_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_status', to='advert_rates.responsestatus', verbose_name='статус ответа')),
                ('telegram_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='advert_rates.telegramuser', verbose_name='пользователь')),
                ('type_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_request', to='advert_rates.typesrequest', verbose_name='тип запроса')),
            ],
            options={
                'db_table': 'telegram_users_requests',
            },
        ),
    ]
